services:
  frontend:
    image: ghcr.io/r1ft1/bonk/frontend:${TAG:-main}
    networks:
      - coolify
      - default
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boop-frontend.rule=Host(`boop.oatmocha.com`) && !PathPrefix(`/ws`) && !PathPrefix(`/getWaitingGame`)"
      - "traefik.http.routers.boop-frontend.entrypoints=https"
      - "traefik.http.routers.boop-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.boop-frontend.loadbalancer.server.port=3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/r1ft1/bonk/backend:${TAG:-main}
    networks:
      - coolify
      - default
    expose:
      - "8080"
    environment:
      - ENV=PROD
      - DB_PATH=/data/games.db
      - ORIGIN_URL=https://boop.oatmocha.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.boop-backend.rule=Host(`boop.oatmocha.com`) && (PathPrefix(`/ws`) || PathPrefix(`/getWaitingGame`))"
      - "traefik.http.routers.boop-backend.priority=100"
      - "traefik.http.routers.boop-backend.entrypoints=https"
      - "traefik.http.routers.boop-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.boop-backend.loadbalancer.server.port=8080"
    volumes:
      - game-data:/data

networks:
  coolify:
    external: true

volumes:
  game-data:
