<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 cat.glb
-->

<script lang="ts">
	import type { Snippet } from "svelte";
	import { Group } from "three";
	import { T } from "@threlte/core";
	import { Outlines, useGltf, Edges } from "@threlte/extras";
	import { animate } from "motion";

	const ref = new Group();

	const gltf = useGltf("/cat.glb");

	let {
		color,
		placed,
		position,
		selectable,
		fallback,
		children,
	}: {
		color: any;
		placed: any;
		position: any;
		selectable: boolean;
		booped?: boolean;
		finalPosition?: any[];
		fallback?: Snippet;
		children?: Snippet<[{ ref: Group }]>;
	} = $props();
</script>

<T is={ref} dispose={false}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cube.geometry}
			material={gltf.nodes.Cube.material}
			{position}
			scale={[0.5, 0.5, 0.5]}
			oncreate={(ref) => {
				if (placed) {
					animate(
						ref.position,
						{ y: 0.52 },
						{
							duration: 1,
							repeat: 0,
							ease: "backInOut",
							type: "spring",
						},
					);
				} else {
					ref.position.y = 0.52;
				}
			}}
		>
			<T.MeshStandardMaterial {color} />
			{#if selectable}
				<Outlines color="white" />
			{:else}
				<Outlines color="black" />
			{/if}
			<Edges color="black" />
		</T.Mesh>
	{:catch _error}
		<!-- no error fallback -->
	{/await}

	{@render children?.({ ref })}
</T>
