<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 cat.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { Outlines, useGltf, Edges } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/cat.glb')

  const component = forwardEventHandlers()

  export let color

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.nodes.Cube.material} position={[0, 1.02, 0]} >
      <T.MeshStandardMaterial color={color} />
			<Outlines color="black" />
      <Edges color="black" />
    </T.Mesh>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
