<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 kitten.glb
-->

<script lang="ts">
	import type { Snippet } from "svelte";
	import { Group } from "three";
	import { T } from "@threlte/core";
	import { useGltf, Outlines } from "@threlte/extras";
	import { animate } from "motion";
	import { gameState } from "./stores.svelte";

	const ref = new Group();

	const gltf = useGltf("/kitten.glb");

	let {
		color,
		placed,
		selectable,
		position,
		booped = false,
		finalPosition = [0, 0, 0],
		fallback,
		children,
	}: {
		color: any;
		placed: boolean;
		selectable: boolean;
		position: any;
		booped?: boolean;
		finalPosition?: any[];
		fallback?: Snippet;
		children?: Snippet<[{ ref: Group }]>;
	} = $props();

	let kittenRef: any;

	// Debug: initial position logged at mount time
	$effect(() => { console.log($gameState.placed.position, position[0], position[2]); });

	$effect(() => {
		if (
			$gameState.placed.position.x == position[0] + 2.5 &&
			$gameState.placed.position.y == position[2] + 2.5
		) {
			console.log("animate kitten placement: ");
			ref.position.y = 1.52;
			animate(
				ref.position,
				{ y: 0.02 },
				{
					duration: 1,
					repeat: 0,
					ease: "backInOut",
					type: "spring",
				},
			);
		}
	});

	$effect(() => {
		if (booped) {
			ref.position.y = position[1];
			ref.position.x = position[0] + 2.5;
			ref.position.z = position[2] + 2.5;
			animate(
				ref.position,
				{
					x: finalPosition[0],
					y: finalPosition[1],
					z: finalPosition[2],
				},
				{
					duration: 1,
					repeat: 0,
					ease: "backInOut",
					type: "spring",
				},
			);
		}
	});

	console.log(ref);
</script>

<T is={ref} dispose={false}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Kitten.geometry}
			material={gltf.nodes.Kitten.material}
			{position}
			scale={[0.5, 0.5, 0.5]}
			oncreate={(ref) => {
				kittenRef = ref;
			}}
		>
			<T.MeshStandardMaterial {color} />
			{#if selectable}
				<Outlines color="white" />
			{:else}
				<Outlines color="black" />
			{/if}
		</T.Mesh>
	{:catch _error}
		<!-- no error fallback -->
	{/await}

	{@render children?.({ ref })}
</T>
