<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 kitten.glb
-->

<script lang="ts">
	import type { Snippet } from "svelte";
	import { Color, Group, Vector3 } from "three";
	import { T, useTask } from "@threlte/core";
	import { useGltf, Outlines } from "@threlte/extras";
	import { animate } from "motion";
	import { gameState, isMobile, placementLanded, animConfig, arcTrigger } from "./stores";

	const LINE_COLORS = ["#00ffff", "#ff00ff", "#ffff00", "#00ff00"];
	const SWAP_PERIOD = 1.5;

	// Spawn positions for arc animation (world coordinates)
	// P1 (top-right of screen) and P2 (bottom-left) given camera at [10,10,10]
	const P1_SPAWN = new Vector3(7, 5, -7);
	const P2_SPAWN = new Vector3(3, 5, 9);

	let time = $state(0);
	let arcStart = { x: 0, y: 0, z: 0 };
	let arcProgress = 0;
	let arcAnimating = false;

	function easeOutCubic(t: number): number {
		return 1 - Math.pow(1 - t, 3);
	}

	const ref = new Group();

	const gltf = useGltf("/kitten.glb");

	let {
		color,
		placed,
		selectable,
		isMiddle = false,
		position,
		booped = false,
		finalPosition = [0, 0, 0],
		fallback,
		children,
	}: {
		color: any;
		placed: boolean;
		selectable: number[];
		isMiddle?: boolean;
		position: any;
		booped?: boolean;
		finalPosition?: any[];
		fallback?: Snippet;
		children?: Snippet<[{ ref: Group }]>;
	} = $props();

	let kittenRef: any;
	let lastArcTurn = -1;

	useTask((delta) => {
		if (selectable.length > 0) time += delta;

		if (arcAnimating) {
			const cfg = $animConfig;
			// Cap delta to prevent skipping the entire arc on frame spikes
			arcProgress += Math.min(delta, 0.05) / cfg.arcDuration;
			// Signal landing slightly early so boops start as piece settles
			if (!$placementLanded && arcProgress >= cfg.arcLandThreshold) {
				$placementLanded = true;
			}
			if (arcProgress >= 1) {
				arcAnimating = false;
				ref.position.set(0, 0, 0);
			} else {
				const t = easeOutCubic(arcProgress);
				ref.position.x = arcStart.x * (1 - t);
				ref.position.z = arcStart.z * (1 - t);
				ref.position.y = arcStart.y * (1 - t) + cfg.arcHeight * 4 * t * (1 - t);
			}
		}
	});

	$effect(() => {
		const trigger = $arcTrigger;
		if (
			trigger.piece !== 0 &&
			trigger.turn !== lastArcTurn &&
			trigger.x == position[0] + 2.5 &&
			trigger.y == position[2] + 2.5
		) {
			lastArcTurn = trigger.turn;
			const targetWorld = new Vector3(position[0], position[1], position[2]);
			// turnNumber already incremented after placement; odd = P1 just played
			const spawn = trigger.turn % 2 === 1 ? P1_SPAWN : P2_SPAWN;

			arcStart = {
				x: spawn.x - targetWorld.x,
				y: spawn.y - targetWorld.y,
				z: spawn.z - targetWorld.z,
			};
			ref.position.set(arcStart.x, arcStart.y, arcStart.z);
			arcProgress = 0;
			arcAnimating = true;
			$placementLanded = false;
		}
	});

	$effect(() => {
		if (booped) {
			ref.position.y = position[1];
			ref.position.x = position[0] + 2.5;
			ref.position.z = position[2] + 2.5;
			animate(
				ref.position,
				{
					x: finalPosition[0],
					y: finalPosition[1],
					z: finalPosition[2],
				},
				{
					duration: 1,
					repeat: 0,
					ease: "backInOut",
					type: "spring",
				},
			);
		}
	});

</script>

<T is={ref} dispose={false}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Kitten.geometry}
			material={gltf.nodes.Kitten.material}
			{position}
			scale={[0.5, 0.5, 0.5]}
			rotation.y={$isMobile ? -Math.PI / 2 : 0}
			oncreate={(ref) => {
				kittenRef = ref;
			}}
		>
			<T.MeshStandardMaterial {color} />
			<Outlines
				color={selectable.length > 0
					? (() => {
						const t = (time / SWAP_PERIOD) % selectable.length;
						const fromIdx = selectable[Math.floor(t) % selectable.length] % LINE_COLORS.length;
						const toIdx = selectable[(Math.floor(t) + 1) % selectable.length] % LINE_COLORS.length;
						const frac = t - Math.floor(t);
						const c = new Color(LINE_COLORS[fromIdx]).lerp(new Color(LINE_COLORS[toIdx]), frac);
						return `#${c.getHexString()}`;
					})()
					: "black"}
				thickness={selectable.length > 0
					? (isMiddle ? 0.12 + 0.04 * Math.sin(time * 3) : 0.06)
					: 0.05}
			/>
		</T.Mesh>
	{:catch _error}
		<!-- no error fallback -->
	{/await}

	{@render children?.({ ref })}
</T>
